version: "3.7"

services:
  db:
    image: "mysql:8.0.15"
    container_name: "eshelf_mysql"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      # MYSQL_ROOT_PASSWORD: "change_this_pretty_bad_password"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "eshelf"
      MYSQL_USER: "eshelf"
      MYSQL_PASSWORD: "change_this_pretty_bad_password"
    volumes:
      - "./db/data:/var/lib/mysql:rw"
    ports:
      - "5001:3306"

  # # FIXME
  # db_admin:
  #   depends_on:
  #     - "db"
  #   image: "phpmyadmin/phpmyadmin:latest"
  #   container_name: "eshelf_phpmyadmin"
  #   entrypoint: "/bin/true"
  #   environment:
  #     - "PMA_ARBITRARY=1"
  #     - "PMA_HOST=eshelf_mysql"
  #     - "PMA_HOST=3306"
  #   ports:
  #     - "5002:80"

  api:
    depends_on:
      - "db"
    build: "./api"
    container_name: "eshelf_api"
    volumes:
      - "./api/api:/usr/src/app"
      - "./conf:/usr/src/app/conf"
    ports:
      - "5000:80"
